#include "capture_program.h"
#include <apio.h>

void capture_program_init(void) {
    APIO_ENABLE_GPIOS();
    APIO_ENABLE_PIOS();
    APIO_GPIO_INIT();
    APIO_GPIO_INPUT_ONLY(CAPTURE_STROBE_PIN);
    APIO_GPIO_PULL_UP(CAPTURE_STROBE_PIN);
    for (int pin = CAPTURE_DATA_BASE;
         pin < CAPTURE_DATA_BASE + CAPTURE_DATA_BITS; ++pin) {
        APIO_GPIO_INPUT_ONLY(pin);
        APIO_GPIO_PULL_DOWN(pin);
    }
#ifdef CAPTURE_W1
    for (int pin = CAPTURE_RW_PIN; pin <= CAPTURE_SELECT_PIN; ++pin) {
        APIO_GPIO_INPUT_ONLY(pin);
        APIO_GPIO_PULL_UP(pin);
    }
#endif
    APIO_ASM_INIT();
    APIO_CLEAR_ALL_IRQS();
    APIO_SET_BLOCK(CAPTURE_PIO);
    APIO_GPIOBASE_0();
    APIO_SET_SM(CAPTURE_SM);
    APIO_WRAP_BOTTOM();
#ifdef CAPTURE_W1
    /* W1 accepts only selected, write, both-lane assertions. These controls
       are established before /AS and held through the low phase by C5. */
    APIO_ADD_INSTR(APIO_WAIT_GPIO_HIGH(CAPTURE_SELECT_PIN));
    APIO_ADD_INSTR(APIO_WAIT_GPIO_LOW(CAPTURE_RW_PIN));
    APIO_ADD_INSTR(APIO_WAIT_GPIO_LOW(CAPTURE_UDS_PIN));
    APIO_ADD_INSTR(APIO_WAIT_GPIO_LOW(CAPTURE_LDS_PIN));
#endif
    APIO_ADD_INSTR(APIO_WAIT_GPIO_LOW(CAPTURE_STROBE_PIN));
    APIO_ADD_INSTR(APIO_IN_PINS(CAPTURE_DATA_BITS));
    APIO_ADD_INSTR(APIO_PUSH_BLOCK);
    APIO_ADD_INSTR(APIO_IRQ_SET(CAPTURE_IRQ));
    /* apio wrap markers precede their endpoint instruction. */
    APIO_WRAP_TOP();
    APIO_ADD_INSTR(APIO_WAIT_GPIO_HIGH(CAPTURE_STROBE_PIN));
    APIO_SM_CLKDIV_SET(1, 0);
    APIO_SM_EXECCTRL_SET(0);
    APIO_SM_SHIFTCTRL_SET(APIO_IN_SHIFTDIR_L);
    APIO_SM_PINCTRL_SET(APIO_IN_BASE(CAPTURE_DATA_BASE));
    APIO_SM_JMP_TO_START();
    APIO_END_BLOCK();
    APIO_ENABLE_SMS(CAPTURE_PIO, (1 << CAPTURE_SM));
}
