# This file is automatically generated by scripts/update_cmake_sources.py
# Do not edit this file directly. Edit the template in build-artifacts/ instead.

project(fujinet_nio
    VERSION 0.1.1
    LANGUAGES C CXX
)

# Configure yaml-cpp to only build the core library, no tests/tools/contrib.
set(YAML_CPP_BUILD_TESTS   OFF CACHE BOOL "Disable yaml-cpp tests"   FORCE)
set(YAML_CPP_BUILD_TOOLS   OFF CACHE BOOL "Disable yaml-cpp tools"   FORCE)
set(YAML_CPP_BUILD_CONTRIB OFF CACHE BOOL "Disable yaml-cpp contrib" FORCE)
set(YAML_BUILD_SHARED_LIBS OFF CACHE BOOL "Build yaml-cpp as static" FORCE)

# Bring in yaml-cpp (third-party YAML library)
add_subdirectory(third_party/yaml-cpp)

# Options
option(FN_BUILD_POSIX_APP     "Build POSIX console application"           ON)
option(FN_BUILD_TESTS         "Build unit tests"                          ON)
option(FN_WITH_CURL           "Enable libcurl-backed HTTP/HTTPS on POSIX" ON)

# Build options, used in build_profile.cpp, these need reflecting in the target_compile_definitions below
# These can then be used as flags for the build type in cmake via CMakePresets.json
option (FN_BUILD_ATARI        "Build for Atari SIO Legacy profile"    OFF)
option (FN_BUILD_FUJIBUS_PTY  "Build for FUJIBUS PTY profile"         OFF)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Enable folders in IDEs
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

# --------------------------------------------------
# Library target: fujinet-nio
# --------------------------------------------------
add_library(fujinet-nio)

# --------------------------------------------------
# CURL
# --------------------------------------------------
if(FN_WITH_CURL)
  find_package(CURL QUIET)
  if(CURL_FOUND)
    target_compile_definitions(fujinet-nio PUBLIC FN_WITH_CURL=1)
    target_link_libraries(fujinet-nio PRIVATE CURL::libcurl)
  else()
    message(WARNING "FN_WITH_CURL=ON but libcurl not found; disabling HTTP/HTTPS backend.")
    target_compile_definitions(fujinet-nio PUBLIC FN_WITH_CURL=0)
  endif()
else()
  target_compile_definitions(fujinet-nio PUBLIC FN_WITH_CURL=0)
endif()

# --------------------------------------------------
# Build Flags
# --------------------------------------------------
target_compile_definitions(fujinet-nio
    PUBLIC
        FN_PLATFORM_POSIX               # always true in this toolchain
        $<$<CONFIG:Debug>:FN_DEBUG>
        $<$<BOOL:${FN_BUILD_ATARI}>:FN_BUILD_ATARI>
        $<$<BOOL:${FN_BUILD_FUJIBUS_PTY}>:FN_BUILD_FUJIBUS_PTY>
        # ADD MORE BUILD OPTIONS AS WE DEVELOP THEM HERE
)

target_sources(fujinet-nio
    PRIVATE
# __TARGET_SOURCES_START__
        src/lib/bootstrap.cpp
        src/lib/build_profile.cpp
        src/lib/clock_device.cpp
        src/lib/clock_device_init.cpp
        src/lib/diagnostic_core_provider.cpp
        src/lib/diagnostic_disk_provider.cpp
        src/lib/diagnostic_network_provider.cpp
        src/lib/diagnostic_registry.cpp
        src/lib/disk/atr_image.cpp
        src/lib/disk/disk_service.cpp
        src/lib/disk/image_registry.cpp
        src/lib/disk/raw_image.cpp
        src/lib/disk/ssd_image.cpp
        src/lib/disk_device.cpp
        src/lib/disk_device_init.cpp
        src/lib/file_device.cpp
        src/lib/file_device_init.cpp
        src/lib/fs_stdio.cpp
        src/lib/fuji_bus_packet.cpp
        src/lib/fuji_config_yaml_store.cpp
        src/lib/fuji_device.cpp
        src/lib/fujibus_transport.cpp
        src/lib/fujinet_core.cpp
        src/lib/fujinet_init.cpp
        src/lib/io_device_manager.cpp
        src/lib/io_service.cpp
        src/lib/network_device.cpp
        src/lib/network_device_init.cpp
        src/lib/network_protocol_registry.cpp
        src/lib/network_protocol_stub.cpp
        src/lib/routing_manager.cpp
        src/lib/storage_manager.cpp
        src/lib/tcp_network_protocol_common.cpp
        src/platform/posix/channel_factory.cpp
        src/platform/posix/console_transport_default.cpp
        src/platform/posix/console_transport_pty.cpp
        src/platform/posix/console_transport_stdio.cpp
        src/platform/posix/disk_registry.cpp
        src/platform/posix/fs_factory.cpp
        src/platform/posix/fuji_config_store_factory.cpp
        src/platform/posix/fuji_device_factory.cpp
        src/platform/posix/hardware_caps.cpp
        src/platform/posix/http_network_protocol_curl.cpp
        src/platform/posix/logging.cpp
        src/platform/posix/network_registry.cpp
        src/platform/posix/tcp_network_protocol_posix.cpp
        src/platform/posix/tcp_socket_ops_posix.cpp
        src/platform/posix/time.cpp
# __TARGET_SOURCES_END__
        third_party/cjson/cJSON.c
)


target_include_directories(fujinet-nio
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/include
    PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}/third_party/cjson
)

target_compile_features(fujinet-nio PUBLIC cxx_std_20)

# Link yaml-cpp
target_link_libraries(fujinet-nio
    PUBLIC
        yaml-cpp
)

# --------------------------------------------------
# POSIX app (Linux/macOS/Windows console)
# --------------------------------------------------
if(FN_BUILD_POSIX_APP)
    add_executable(fujinet-nio-posix
        src/app/main_posix.cpp
    )

    target_sources(fujinet-nio-posix
        PRIVATE
# __POSIX_APP_SOURCES_START__
            src/app/console_commands.cpp
            src/app/console_engine.cpp
            src/app/console_fs_shell.cpp
            src/app/console_parse.cpp
# __POSIX_APP_SOURCES_END__
    )

    target_link_libraries(fujinet-nio-posix
        PRIVATE
            fujinet-nio
    )

    set_target_properties(fujinet-nio-posix PROPERTIES
        OUTPUT_NAME "fujinet-nio"
    )

    # Copy a small runner script next to the built binary (for "reboot" restarts on EX_TEMPFAIL=75).
    add_custom_command(TARGET fujinet-nio-posix POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            ${CMAKE_SOURCE_DIR}/distfiles/run-fujinet-nio
            $<TARGET_FILE_DIR:fujinet-nio-posix>/run-fujinet-nio
        COMMAND /bin/chmod +x
            $<TARGET_FILE_DIR:fujinet-nio-posix>/run-fujinet-nio
        VERBATIM
    )
endif()

# --------------------------------------------------
# Tests (using CTest/doctest)
# --------------------------------------------------
if(FN_BUILD_TESTS)
    enable_testing()
    add_subdirectory(tests)
endif()
