# Build upstream source, including the sole APIO_EMU_IMPL in epio_apio.c.
file(GLOB EPIO_SOURCES CONFIGURE_DEPENDS "${DEPS}/epio/src/*.c")
add_library(epio STATIC ${EPIO_SOURCES})
add_dependencies(epio bridge_validate)
target_include_directories(epio PUBLIC "${DEPS}/epio/include" "${DEPS}/apio/include")
target_compile_definitions(epio PUBLIC APIO_EMULATION=1)
# epio exposes enum-bearing structs; consumers must use the same ABI.
target_compile_options(epio PUBLIC -fshort-enums)
add_executable(test_capture tests/test_capture.c src/capture_program.c)
add_dependencies(test_capture bridge_validate)
target_include_directories(test_capture PRIVATE src)
target_link_libraries(test_capture PRIVATE epio)
target_compile_options(test_capture PRIVATE -Wall -Wextra -Werror)
add_test(NAME capture COMMAND test_capture)
add_executable(test_capture_idle tests/test_capture_idle.c src/capture_program.c)
add_dependencies(test_capture_idle bridge_validate)
target_include_directories(test_capture_idle PRIVATE src)
target_link_libraries(test_capture_idle PRIVATE epio)
target_compile_options(test_capture_idle PRIVATE -Wall -Wextra -Werror)
add_test(NAME capture_idle COMMAND test_capture_idle)
add_executable(test_capture_patterns tests/test_capture_patterns.c src/capture_program.c)
add_dependencies(test_capture_patterns bridge_validate)
target_include_directories(test_capture_patterns PRIVATE src)
target_link_libraries(test_capture_patterns PRIVATE epio)
target_compile_options(test_capture_patterns PRIVATE -Wall -Wextra -Werror)
add_test(NAME capture_patterns COMMAND test_capture_patterns)
add_test(NAME tooling COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_tooling.py")
add_test(NAME pio_policy COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/scripts/check_pio_policy.py")
function(add_stimulus_test experiment test_target test_name words samples)
    add_executable(${test_target} tests/feasibility/test_stimulus.c
        tests/feasibility/${experiment}/src/stimulus_program.c
        tests/feasibility/${experiment}/src/stimulus_expectations.c
        lab/rp2040/stimulus_control.c)
    add_dependencies(${test_target} bridge_validate)
    target_include_directories(${test_target} PRIVATE lab/rp2040 tests/feasibility)
    target_link_libraries(${test_target} PRIVATE epio)
    target_compile_options(${test_target} PRIVATE -Wall -Wextra -Werror)
    target_compile_definitions(${test_target} PRIVATE STIMULUS_WORDS=${words}
        STIMULUS_SAMPLE_COUNT=${samples})
    add_test(NAME ${test_name} COMMAND ${test_target})
endfunction()
include(cmake/stimulus_tests.cmake)
add_test(NAME experiment_runner COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/feasibility/test_experiment.py")
add_test(NAME experiment_runner_optimized COMMAND "${Python3_EXECUTABLE}" -O "${CMAKE_CURRENT_SOURCE_DIR}/tests/feasibility/test_experiment.py")
add_test(NAME report_summary COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/feasibility/test_report_summary.py")

add_test(NAME setup COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_setup.py")
