if(NOT PICO_RP2040)
    message(FATAL_ERROR "Stimulus requires RP2040")
endif()
set(STIMULUS_EXPERIMENT "generator-check" CACHE STRING "Experiment stimulus source directory")
set(STIMULUS_TARGET "feasibility_stimulus" CACHE STRING "Experiment firmware target")
if(NOT STIMULUS_EXPERIMENT MATCHES "^(generator-check|C0-idle)$")
    message(FATAL_ERROR "Unsupported stimulus experiment: ${STIMULUS_EXPERIMENT}")
endif()
add_executable(${STIMULUS_TARGET} lab/rp2040/main.c
    tests/feasibility/${STIMULUS_EXPERIMENT}/src/stimulus_program.c lab/rp2040/stimulus_control.c)
add_dependencies(${STIMULUS_TARGET} bridge_validate)
target_include_directories(${STIMULUS_TARGET} PRIVATE lab/rp2040 "${DEPS}/apio/include")
target_link_libraries(${STIMULUS_TARGET} PRIVATE pico_stdlib hardware_pio hardware_clocks)
target_compile_options(${STIMULUS_TARGET} PRIVATE -Wall -Wextra -Werror)
pico_enable_stdio_uart(${STIMULUS_TARGET} 0)
pico_enable_stdio_usb(${STIMULUS_TARGET} 1)
# No flash identification/boot-stage assumptions; ROM loads this image into SRAM.
pico_set_binary_type(${STIMULUS_TARGET} no_flash)
pico_add_extra_outputs(${STIMULUS_TARGET})
