# Catch accidental leakage even when FN_BUILD_TESTS is enabled in a normal build.
set(binaries "${PRODUCTION_LIBRARY}" "${NATIVE_RUNNER}" "${UNIT_TESTS}")
if(DEFINED PRODUCTION_APP)
    list(APPEND binaries "${PRODUCTION_APP}")
endif()
foreach(binary IN LISTS binaries)
    execute_process(COMMAND "${NM}" -C "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE symbols ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot inspect ${binary}: ${error}")
    endif()
    foreach(symbol IN ITEMS set_test_unix_time_seconds g_test_unix_time)
        string(FIND "${symbols}" "${symbol}" position)
        if(binary STREQUAL UNIT_TESTS)
            if(position EQUAL -1)
                message(FATAL_ERROR "Missing test clock ${symbol} in ${binary}")
            endif()
        elseif(NOT position EQUAL -1)
            message(FATAL_ERROR "Test clock ${symbol} leaked into ${binary}")
        endif()
    endforeach()
endforeach()
