[platformio]
default_envs = link-esp32s3
src_dir = src
core_dir = ${PROJECT_DIR}/.pio-core

[env:link-esp32s3]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = espidf
build_type = debug
board_build.sdkconfig = sdkconfig.defaults
build_flags =
    -I ${PROJECT_DIR}/../link-common
    -D LINK_ESP_SCLK_PIN=12
    -D LINK_ESP_MOSI_PIN=11
    -D LINK_ESP_MISO_PIN=13
    -D LINK_ESP_CS_PIN=10
    -D LINK_ESP_READY_PIN=9
    -D LINK_ESP_DATA_AVAILABLE_PIN=8
    -D LINK_DEFAULT_SCENARIO=${sysenv.LINK_DEFAULT_SCENARIO}
monitor_speed = 115200
