@startuml
title IO Protocols (auto-gen from clang-uml)
enum "io::protocol::WireDeviceId" as C_0015225225004340369839
enum C_0015225225004340369839 {
FujiNet
DiskFirst
DiskLast
PrinterFirst
PrinterLast
Voice
Clock
NetworkFirst
NetworkLast
Midi
Dbc
FileService
}
enum "io::protocol::SlipByte" as C_0010627602090167488081
enum C_0010627602090167488081 {
End
Escape
EscEnd
EscEsc
}
class "io::protocol::PacketParam" as C_0003277087640557799971
class C_0003277087640557799971 {
+PacketParam(std::uint32_t v, std::uint8_t s) : void
+PacketParam<T>(T v) : void
__
+size : std::uint8_t
+value : std::uint32_t
}
class "io::protocol::FujiBusPacket" as C_0017232777488057089840
class C_0017232777488057089840 {
+FujiBusPacket() = default : void
+FujiBusPacket<Args...>(WireDeviceId dev, std::uint8_t cmd, Args &&... args) : void
..
+addParamU16(std::uint16_t v) : FujiBusPacket &
+addParamU32(std::uint32_t v) : FujiBusPacket &
+addParamU8(std::uint8_t v) : FujiBusPacket &
-calcChecksum(const ByteBuffer & buf) const : std::uint8_t
+clearData() : FujiBusPacket &
+command() const : std::uint8_t
+data() const : const std::optional<ByteBuffer> &
+dataAsString() const : std::optional<std::string>
-decodeSLIP(const ByteBuffer & input) const : ByteBuffer
+device() const : WireDeviceId
-encodeSLIP(const ByteBuffer & input) const : ByteBuffer
{static} +fromSerialized(const ByteBuffer & input) : std::unique_ptr<FujiBusPacket>
+param(unsigned int index) const : std::uint32_t
+paramCount() const : unsigned int
-parse(const ByteBuffer & input) : bool
-processArg(const std::string & s) : void
-processArg(ByteBuffer && buf) : void
-processArg(const ByteBuffer & buf) : void
-processArg(std::uint32_t v) : void
-processArg(std::uint16_t v) : void
-processArg(std::uint8_t v) : void
+serialize() const : ByteBuffer
+setData(ByteBuffer data) : FujiBusPacket &
+tryParamU8(unsigned int index, std::uint8_t & out) const : bool
__
-_command : std::uint8_t
-_data : std::optional<ByteBuffer>
-_device : WireDeviceId
-_params : std::vector<PacketParam>
}
class "io::protocol::FujiBusHeader" as C_0009954510640382192371
class C_0009954510640382192371 {
__
+checksum : std::uint8_t
+command : std::uint8_t
+descr : std::uint8_t
+device : std::uint8_t
+length : std::uint16_t
}
enum "io::protocol::FileCommand" as C_0003895064208135060769
enum C_0003895064208135060769 {
Stat
ListDirectory
ReadFile
WriteFile
}
enum "io::protocol::FujiCommand" as C_0004628219160953719395
enum C_0004628219160953719395 {
Reset
GetSsid
}
C_0017232777488057089840 o-- C_0015225225004340369839 : -_device
C_0017232777488057089840 o-- C_0003277087640557799971 : -_params

'Generated with clang-uml, version 0.6.2
'LLVM version Ubuntu clang version 18.1.3 (1ubuntu1)
@enduml
